# Generated by Django 4.0.6 on 2022-10-22 18:16

from django.db import migrations, models
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(null=True, upload_to=None)),
                ('description', models.TextField()),
                ('prev_work', models.ImageField(null=True, upload_to=None)),
                ('por_txt', models.TextField()),
                ('por_img', models.ImageField(null=True, upload_to=None)),
                ('recruit_link', models.URLField(null=True)),
                ('event_details', models.TextField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('skill', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
