# Generated by Django 4.0.6 on 2022-10-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClubForm',
            new_name='Club',
        ),
    ]
